name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install deps
        run: npm install

      - name: Build
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Upload dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist

      - run: ls

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          clean: true
          clean-exclude: |
            CNAME